---

- name: Install from binary when architecture is ARM
  block:
    - name: Download archived binary
      get_url:
        url: "{{ chronograf_binary_arm }}"
        dest: "{{ chronograf_download_destination }}"
        checksum: "sha256:{{chronograf_binary_arm_checksum }}"

    - name: Install archived binary
      become: yes
      unarchive:
        src: "{{ chronograf_download_destination }}"
        dest: "{{ chronograf_install_location }}"
        remote_src: yes

    - name: Add service
      become: yes
      template:
        src: chronograf.service.j2
        dest: "/etc/systemd/system/{{ chronograf_service_name }}.service"

    - name: Run service
      become: yes
      systemd:
        name: "{{ chronograf_service_name }}"
        state: started
        daemon_reload: yes
        enabled: yes
  when: ansible_architecture.find('v=' ~ 'arm') == -1
