---

- name: Install from binary when architecture is ARM
  block:
    - name: Download archived binary
      get_url:
        url: "{{ chronograph_binary_arm }}"
        dest: "{{ chronograph_download_destination }}"
        checksum: "sha256:{{chronograph_binary_arm_checksum }}"

    - name: Install archived binary
      become: yes
      unarchive:
        src: "{{ chronograph_download_destination }}"
        dest: "{{ chronograph_binary_location }}"
        remote_src: yes

    - name: Add service
      become: yes
      template:
        src: chronograf.service.j2
        dest: /etc/systemd/system/chronograf.service

    - name: Run service
      become: yes
      systemd:
        name: chronograf
        state: started
        daemon_reload: yes
        enabled: yes
  when: ansible_architecture.find('v=' ~ 'arm') == -1
